import type { Metadata } from "next";

import "@/styles/globals.css";
import { Inter } from "next/font/google";
import "react-quill/dist/quill.snow.css";

import AuthProvider from "./components/auth/AuthProvider";
import AxiosProvider from "./components/provider/AxiosProvider";
import ReactQueryProviders from "./components/provider/QueryProvider";
import ReduxProvider from "./components/provider/redux";

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
  modal,
}: {
  children: React.ReactNode;
  modal: React.ReactNode;
}) {
  return (
    <html lang="ko">
      <ReactQueryProviders>
        <AuthProvider>
          <AxiosProvider>
            <ReduxProvider>
              <body>
                {children}
                {modal}
              </body>
            </ReduxProvider>
          </AxiosProvider>
        </AuthProvider>
      </ReactQueryProviders>
    </html>
  );
}
