import type { Metadata } from "next";

import "@/styles/globals.css";
import { config } from "@fortawesome/fontawesome-svg-core";
import "@fortawesome/fontawesome-svg-core/styles.css";
import { Inter } from "next/font/google";
import "react-quill/dist/quill.snow.css";

import AuthProvider from "@/components/auth/AuthProvider";
import ReactQueryProviders from "@/components/provider/reactQuery";
import ReduxProvider from "@/components/provider/redux";

config.autoAddCss = false;

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
  modal,
}: {
  children: React.ReactNode;
  modal: React.ReactNode;
}) {
  return (
    <html lang="en">
      <body>
        <AuthProvider>
          <ReactQueryProviders>
            <ReduxProvider>
              {modal}
              {children}
            </ReduxProvider>
          </ReactQueryProviders>
        </AuthProvider>
      </body>
    </html>
  );
}
